apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops-container
        image: mlops-app:latest
        imagePullPolicy: IfNotPresent